"""add_rules_table

Revision ID: 03765d17d6b2
Revises: efa9912b20ca
Create Date: 2026-02-13 17:16:35.245714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03765d17d6b2'
down_revision: Union[str, Sequence[str], None] = 'efa9912b20ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('published', sa.Integer(), server_default='1', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_domain_events_entity', 'domain_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_domain_events_tenant_time', 'domain_events', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('idx_domain_events_type_time', 'domain_events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_id'), 'domain_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_type'), 'domain_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_events_tenant_id'), 'domain_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_domain_events_timestamp'), 'domain_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_domain_events_user_id'), 'domain_events', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type_filter', sa.String(), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_event_type_filter'), 'rules', ['event_type_filter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_event_type_filter'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_domain_events_user_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_timestamp'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_tenant_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_id'), table_name='domain_events')
    op.drop_index('idx_domain_events_type_time', table_name='domain_events')
    op.drop_index('idx_domain_events_tenant_time', table_name='domain_events')
    op.drop_index('idx_domain_events_entity', table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
