"""Add Evolution and AB Testing models

Revision ID: 2b863a3c9f73
Revises: a260d4a16f69
Create Date: 2026-02-19 20:02:45.022997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b863a3c9f73'
down_revision: Union[str, Sequence[str], None] = 'a260d4a16f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
