"""Add outcome correlation models

Revision ID: f81871248024
Revises: 3499696f31cd
Create Date: 2026-02-19 19:48:32.302593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81871248024'
down_revision: Union[str, Sequence[str], None] = '3499696f31cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_events_session_id'), 'context_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_context_events_source'), 'context_events', ['source'], unique=False)
    op.create_index(op.f('ix_context_events_source_id'), 'context_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_context_events_timestamp'), 'context_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_context_events_user_id'), 'context_events', ['user_id'], unique=False)
    op.create_table('context_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('context_event_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_event_id'], ['context_events.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_links_context_event_id'), 'context_links', ['context_event_id'], unique=False)
    op.create_index(op.f('ix_context_links_trace_id'), 'context_links', ['trace_id'], unique=False)
    op.create_table('nudge_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True).with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nudge_logs_trace_id'), 'nudge_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_nudge_logs_user_id'), 'nudge_logs', ['user_id'], unique=False)
    op.add_column('decision_traces', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_decision_traces_user_id'), 'decision_traces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_traces_user_id'), table_name='decision_traces')
    op.drop_column('decision_traces', 'user_id')
    op.drop_index(op.f('ix_nudge_logs_user_id'), table_name='nudge_logs')
    op.drop_index(op.f('ix_nudge_logs_trace_id'), table_name='nudge_logs')
    op.drop_table('nudge_logs')
    op.drop_index(op.f('ix_context_links_trace_id'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_context_event_id'), table_name='context_links')
    op.drop_table('context_links')
    op.drop_index(op.f('ix_context_events_user_id'), table_name='context_events')
    op.drop_index(op.f('ix_context_events_timestamp'), table_name='context_events')
    op.drop_index(op.f('ix_context_events_source_id'), table_name='context_events')
    op.drop_index(op.f('ix_context_events_source'), table_name='context_events')
    op.drop_index(op.f('ix_context_events_session_id'), table_name='context_events')
    op.drop_table('context_events')
    # ### end Alembic commands ###
